bark:
  - https://bark.helson-lin.cn/EAhxuqThBQfWfbSfyYqwxk/$TITLE$/$CONTENT$?icon=https://day.app/assets/images/avatar.jpg
emails:
  - name: "Mail"
    host: "imap.163.com"
    port: 993
    username: "xxx@163.com"
    password: "xxx"
    use_tls: true
